version: "3.8"
services:
  acme-backend:
    build: ..
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: acme_db
      MYSQL_USER: acme
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password